sudo: required
language: java
jdk: oraclejdk8

services:
  - docker

cache:
  directories:
    - node_modules

before_install:
  - npm i -g npm@latest

env:
  global:
    - secure: "encrypted-sonar-token"
    - secure: "encrypted-dockerhub-username"
    - secure: "encrypted-dockerhub-password"
    - secure: "encrypted-heroku-api-key"
    - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: "vohra01-github"
    token:
      secure: $SONAR_TOKEN

script:
  - ./mvnw spring-boot:run
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - - npm run lint:ci
    - npm run build:prod

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH&amp;amp;amp;amp;amp;amp;amp;lt;span data-mce-type="bookmark" style="display: inline-block; width: 0px; overflow: hidden; line-height: 0;" class="mce_SELRES_start"&amp;amp;amp;amp;amp;amp;amp;gt;&amp;amp;amp;amp;amp;amp;amp;lt;/span&amp;amp;amp;amp;amp;amp;amp;gt;; fi`
  - export IMAGE_NAME=parking-demo
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: parking-demo
